services:
  wally-backend:
    image: ghcr.io/pathos-iii-krescent/wally:latest
    environment:
      - WALLY_auth=${WALLY_auth}
      - WALLY_github_token=${WALLY_github_token}
    volumes:
      - wally-volume:/app
    ports:
      - "8000:8000"
    networks:
      - traefik
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.wally.rule: "Host(`wally.pathos.gg`)"
        traefik.http.services.wally.loadbalancer.server.port: 8000

networks:
  traefik:
    external: true

volumes:
  wally-volume:
